Anteriores trabajos:
Atacadon:arreglo o mesa.  Atencion a público. 
Pesar as productos igienisacion o mesas e Anaqueles
 Artezania, circo o rua. 
Roraima:Cesko, capino, troko, cargo agua, fazo gayinero
Cuido animales. 
Venezuela Caracas:av baral venda o frutas. 
Venezuela caracas:av San martin. Maternidad. panaderia, atencion a publico. 
Venezuela caracas:parque Carabobo rua la monrroi restaurante Gallego. 
Ayudante de cocaína. 
Venezuela. Caracas:parque Carabobo. Rua a monrroi
Almacen de roupa,  atencion a público. 
Venezuela Merida, la burra.  miel café.ajudante de cosina 
